apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: e6d1ba2d-765c-4128-9af8-d1912089fbf8
    workflow_id: c575c6c0-f023-4b54-852a-ad96275b0468
  name: podtato-head-chaos-1643277343
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: argowf-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: argowf-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-application
        template: install-application
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-delete
        template: pod-delete
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
      - arguments: {}
        name: delete-application
        template: delete-application
  - arguments: {}
    container:
      args:
      - -namespace={{workflow.parameters.adminModeNamespace}}
      - -typeName=resilient
      - -operation=apply
      - -timeout=400
      - -app=podtato-head
      - -scope=namespace
      image: litmuschaos/litmus-app-deployer:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: install-application
    outputs: {}
  - arguments: {}
    container:
      args:
      - kubectl apply -f https://hub.litmuschaos.io/api/chaos/1.13.7?file=charts/generic/experiments.yaml -n {{workflow.parameters.adminModeNamespace}} ; sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/chaosengine.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: podtato-main-pod-delete-chaos-1643277330
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                context: "{{workflow.parameters.adminModeNamespace}}_podtato-main"
            spec:
              appinfo:
                appns: "{{workflow.parameters.adminModeNamespace}}"
                applabel: name=podtato-main
                appkind: deployment
              engineState: active
              chaosServiceAccount: litmus-admin
              jobCleanUpPolicy: retain
              components:
                runner:
                  imagePullPolicy: Always
              experiments:
                - name: pod-delete
                  spec:
                    probe:
                      - name: check-podtato-main-access-url
                        type: httpProbe
                        httpProbe/inputs:
                          url: http://podtato-main.{{workflow.parameters.adminModeNamespace}}.svc.cluster.local:9000
                          insecureSkipVerify: false
                          method:
                            get:
                              criteria: ==
                              responseCode: "200"
                        mode: Continuous
                        runProperties:
                          probeTimeout: 1
                          interval: 1
                          retry: 1
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: FORCE
                          value: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-delete
    outputs: {}
  - arguments: {}
    container:
      args:
      - -namespace={{workflow.parameters.adminModeNamespace}}
      - -typeName=resilient
      - -operation=delete
      - -app=podtato-head
      image: litmuschaos/litmus-app-deployer:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: delete-application
    outputs: {}
  - arguments: {}
    container:
      args:
      - kubectl delete chaosengine podtato-main-pod-delete-chaos-1643277330  -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
